peso=int(input("Qual é o peso?"))
altura=int(input("Qual é a altura"))
imc=int(peso/altura*altura)
if(imc<18.5):
    print("Omelete com 3 ovos, queijo e espinafre")
    print("Sanduíche de atum com maionese e alface")
    print("Macarrão integral com molho de carne ou frango desfiado")
    peso2=int(input("comovc predente perder kilos?"))
    peso2=21.75*(altura*altura)
    objetivo=int(peso-peso2)
    print("vc precisa perder ou ganhar" + str(objetivo) + " peso")
if(imc>18.5 and imc<24.9):
    print("Vitamina de banana com aveia e leite desnatado")
    print("Quinoa ou arroz integral e Quinoa ou arroz integral")
    print("Salada de folhas verdes")
    peso2=int(input("como vc predente perder kilos?"))
    peso2=21.75*(altura*altura)
    objetivo=int(peso-peso2)
    print("vc precisa perder ou ganhar" + str(objetivo) + " peso")
if(imc>25 and imc<29.9):
    print(" pote de iogurte desnatado com 1 colher de granola sem açúcar")
    print("filé de frango grelhado colheres de sopa de arroz integral Carne magra grelhada (patinho ou alcatra)")
    print("pera + 1 torrada integral Omelete de claras com espinafre")
    peso2=int(input("como vc predente perder kilos?"))
    peso2=21.75*(altura*altura)
    objetivo=int(peso-peso2)
    print("vc precisa perder ou ganhar" + str(objetivo) + " peso")
if(imc>30 and imc<34.9):
    print("ovo cozido")
    print("fatia de melancia")
    print("Omelete com espinafre e tomate")
    peso2=int(input("como vc predente perder kilos?"))
    peso2=21.75*(altura*altura)
    objetivo=int(peso-peso2)
    print("vc precisa perder ou ganhar" + str(objetivo) + " peso")
if(imc>35 and imc<39.9):
    print("2 torradas integrais com homus")
    print("Iogurte vegetal com chia")
    print("fatia de pão integral com pasta de abacate")
    peso2=int(input("como vc predente perder kilos?"))
    peso2=21.75*(altura*altura)
    objetivo=int(peso-peso2)
    print("vc precisa perder ou ganhar" + str(objetivo) + " peso")
if(imc>40 and imc<50):
    print("Arroz integral")
    print("Iogurte vegetal com chia")
    print("Sopa de abóbora com gengibre")
    peso2=int(input("como vc predente perder kilos?"))
    peso2=21.75*(altura*altura)
    objetivo=int(peso-peso2)
    print("vc precisa perder ou ganhar" + str(objetivo) + " peso")
if(imc>50):
    print("xícara de chá de hibisco")
    print("Grão-de-bico cozido")
    print("Sopa de legumes com carne magra (sem batata)")
    peso2=int(input("como vc predente perder kilos?"))
    peso2=21.75*(altura*altura)
    objetivo=int(peso-peso2)
    print("vc precisa perder ou ganhar" + str(objetivo) + " peso")